pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                  cd app/backend
                  npm install
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t backend:ci -f docker/backend/Dockerfile .
                '''
            }
        }
    }
}

